include: package:flutter_lints/flutter.yaml

linter:
  rules:
    use_key_in_widget_constructors: false
    prefer_const_constructors: false
    prefer_const_literals_to_create_immutables: false
    avoid_print: false
    always_declare_return_types: true
    avoid_redundant_argument_values: true
    avoid_annotating_with_dynamic: true
    require_trailing_commas: true

analyzer:
  exclude:
    - "**.g.dart"